### ISSUE TITLE
Enhance target specs in YAML to distinguish between "inputs" and "other dependencies"

### ISSUE THREAD

**Issue by rcook** [rcook/pansite#1]
The `routes.yaml` schema looks something like:

```yaml
routes:
- path: content/ctp
  target: ctp.html
- path: content/pcph
  target: pcph.html

targets:
- path: ctp.html
  build-tool: pandoc
  dependencies:
  - ctp.md
- path: pcph.html
  build-tool: pandoc
  dependencies:
  - pcph.md
```

For targets defined in the `targets` section, we should distinguish between "inputs" (which are dependencies for the build tool and which will be passed to the build tool) and "other dependencies" (which are also dependencies for the build tool but which are not passed to the build tool's invocation), e.g.:

```yaml
routes:
- path: content/ctp
  target: ctp.html
- path: content/pcph
  target: pcph.html

targets:
- path: ctp.html
  build-tool: pandoc
  inputs:
  - ctp-section1.md
  - ctp-section2.md
  - ctp-section3.md
  other-dependencies:
  - logo.png
  - document.pdf
- path: pcph.html
  build-tool: pandoc
  inputs:
  - pcph.md
```
